package com.pmfb.gonogo.engine;

import com.pmfb.gonogo.engine.report.WeeklyDigestData;
import com.pmfb.gonogo.engine.exception.WeeklyDigestException;
import com.pmfb.gonogo.engine.report.WeeklyDigestGenerator;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.concurrent.Callable;
import picocli.CommandLine.Command;
import picocli.CommandLine.Option;

@Command(
        name = "weekly-digest",
        description = "Generate a weekly markdown digest from a batch evaluation JSON report."
)
public final class WeeklyDigestCommand implements Callable<Integer> {
    @Option(
            names = {"--input-json"},
            description = "Input JSON report generated by evaluate-batch.",
            required = true
    )
    private Path inputJson;

    @Option(
            names = {"--output-file"},
            description = "Output markdown digest file.",
            defaultValue = "output/weekly.md"
    )
    private Path outputFile;

    @Option(
            names = {"--top-per-section"},
            description = "Max items to include in each verdict section.",
            defaultValue = "5"
    )
    private int topPerSection;

    @Override
    public Integer call() {
        String content;
        try {
            content = Files.readString(inputJson, StandardCharsets.UTF_8);
        } catch (IOException e) {
            System.err.println("Failed to read input JSON '" + inputJson + "': " + e.getMessage());
            return 1;
        }

        WeeklyDigestGenerator generator = new WeeklyDigestGenerator();
        WeeklyDigestData data;
        try {
            data = generator.fromBatchReportJson(inputJson.toString(), content);
        } catch (WeeklyDigestException e) {
            System.err.println("Weekly digest generation failed with " + e.errors().size() + " error(s):");
            for (String error : e.errors()) {
                System.err.println(" - " + error);
            }
            return 1;
        }

        String markdown = generator.toMarkdown(data, topPerSection);
        try {
            Path parent = outputFile.getParent();
            if (parent != null) {
                Files.createDirectories(parent);
            }
            Files.writeString(outputFile, markdown, StandardCharsets.UTF_8);
        } catch (IOException e) {
            System.err.println("Failed to write output markdown '" + outputFile + "': " + e.getMessage());
            return 1;
        }

        System.out.println("Weekly digest generated: " + outputFile);
        System.out.println("source_report: " + inputJson);
        System.out.println("evaluated: " + data.items().size());
        System.out.println("parsing_errors: " + data.errors().size());
        return 0;
    }
}
